import java.util.Random;
import java.util.Scanner;

public class RockPaperScissors {
    //Create a function which simulates the game "rock, paper, scissors".
    // The function takes the input of both players (rock, paper or scissors), first parameter from first player, second from second player. The function returns the result as such:
    //"Player 1 wins"
    //"Player 2 wins"
    //"TIE" (if both inputs are the same)
    //The rules of rock, paper, scissors, if not known:
    //
    //Both players have to say either "rock", "paper" or "scissors" at the same time.
    //Rock beats scissors, paper beats rock, scissors beat paper.
    //Examples
    //rps("rock", "paper") ➞ "Player 2 wins"
    //
    //rps("paper", "rock") ➞ "Player 1 wins"
    //
    //rps("paper", "scissors") ➞ "Player 2 wins"
    //
    //rps("scissors", "scissors") ➞ "TIE"
    //
    //rps("scissors", "paper") ➞ "Player 1 wins"

    public static String gameFunc(){
        String [] choices = {"rock", "paper", "scissors"};

        Random random = new Random();
        int indexChoice = random.nextInt(choices.length);

        return choices[indexChoice];

    }

    private static boolean isValidChoice(String choice) {
        return choice.equals("rock") || choice.equals("paper") || choice.equals("scissors");
    }

    public static void main(String[] args) {
        Scanner scanner = new Scanner(System.in);

        System.out.println("Enter a choice among: (rock, paper, scissors)");

        String choice = scanner.nextLine().toLowerCase();
        String [] choices = {"rock", "paper", "scissors"};
        if (!isValidChoice(choice)){
            System.out.println("Invalid choice");
        }else {
            System.out.println("Its valid.");
        }

        System.out.println(winningFunc(choice));
        scanner.close();
    }

    public static String winningFunc(String choice){
        String ComputerGenerated = gameFunc();
        System.out.println("Generated by the you: " + choice);
        System.out.println("Generated by the computer: " + ComputerGenerated);

        if(choice.equals(ComputerGenerated)){
            return "Its a Tie";
        } else if ((choice.equals("paper") && ComputerGenerated.equals("rock")) ||
                    (choice.equals("scissors") && ComputerGenerated.equals("paper")) ||
                    (choice.equals("rock") && ComputerGenerated.equals("scissors"))){

            return "You win";

        }
        return "The computer wins";
    }


}
